# Isopsephical riddles in the Greek Pseudo Sibylline hexameter poetry

## Introduction

I'll take these three parts under the investigation in this study:

### Riddle 1

#### Sibyl Book 1 lines 137 - 146:


<blockquote><pre>
137 εἰμὶ δ᾿ ἔγωγε ὁ ὤν, σὺ δ᾿ ἐνί φρεσὶ σῇσι νόησον·
138 οὐρανὸν ἐνδέδυμαι, περιβέβλημαι δὲ θάλασσαν,
139 γαῖα δέ μοι στήριγμα ποδῶν, περὶ σῶμα κέχυται
140 ἀὴρ ἠδ᾿ ἄστρων με χορὸς περιδέδρομε πάντη.
141 ἐννέα γράμματ᾿ ἔχω· τετρασύλλαβός εἰμι· νόει με·
142 αἱ τρεῖς αἱ πρῶται δύο γράμματ᾿ ἔχουσιν ἑκάστη,
143 ἡ λοιπὴ δὲ τὰ λοιπὰ καί εἰσιν ἄφωνα τὰ πέντε·
144 τοῦ παντὸς δ᾿ ἀριθμοῦ ἑκατοντάδες εἰσὶ δὶς ὀκτώ
145 καὶ τρεῖς, τρὶς δεκάδες σύν γ᾿ ἑπτά. γνοὺς δὲ τίς εἰμι
146 οὐκ ἀμύητος ἔσῃ τῆς παρ᾿ ἐμοὶ σοφίης.</pre>
</blockquote>

Translation:

<blockquote>
And I am He who is, and in thy heart
Do thou discern. I clothe me with the heaven,
And cast the sea around me, and for me
Earth is a footstool, and the air is poured
Around my body; and on every side
Around me runs the chorus of the stars.
Nine letters have I; of four syllables
I am; discern me. The first three have each
Two letters, the remaining one the rest,
And five are mates; and of the entire sum
The hundreds are twice eight and thrice three tens
Along with seven. Now, knowing who I am,
Be thou not uninitiate in my lore.
</blockquote>

### Riddle 2

#### Sibyl Book 1 lines xyz:

### Riddle 3

#### Sibyl Book 3 lines xyz:

## Process Greek Text Corpora

I have used the next notebook to prepare the greek text corpora and unique words database for the task: 

Setup of the system I'm using is:

In [1]:
import sys
sys.version

'3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 13:41:13) [MSC v.1900 64 bit (AMD64)]'

Confirm unique words database is available and get the size of it:

In [2]:
# to get file size, python 3.4+ version
from pathlib import Path
def get_file_size(f):
    file = Path() / f
    size = file.stat().st_size
    return round(size/1024/1024, 2)

# unique greek words database
csv_file_name = "greek_words_corpora.csv"

print("Size of the unique words database: %s MB" % get_file_size(csv_file_name))

Size of the unique words database: 57.19 MB

## Import database

Using `Pandas` library I will read and import csv file that contains all preprocessed unique greek words collected earlier. Constructed `Pandas DataFrame` is a nice data container to handle tabular data.

In [3]:
# read unique words stats if available
try:
    from pandas import read_csv
    df = read_csv(csv_file_name, header = None)
    # convert data types for columns. 0 = word
    # 1: how many times word occurs in texts
    df[1] = df[1].apply(lambda x: int(x))
    # 2: percentage of all words
    df[2] = df[2].apply(lambda x: float(x))
    # 3: how many characters in the word
    df[3] = df[3].apply(lambda x: int(x))
    # 4: isopsephical value of the word
    df[4] = df[4].apply(lambda x: int(x))
    # 5: word split to syllables
    df[5] = df[5].apply(lambda x: str(x).replace("'", "").replace("[", "").replace("]", "").split(", "))
    # 6: how many syllables
    df[6] = df[6].apply(lambda x: int(x))
except Exception as e:
    print(e)
    print("Could not find unique words database. Please follow the procedure explained in ...")

To confirm succesful import I will show the first 20 most common words:

In [4]:
print("Total records: %s" % len(df))
# get the most repeated words by sort asc, head 20
df.sort_values(1, ascending=False).head(n=20)

Total records: 825088

        0        1     2  3     4       5  6
38    ΚΑΙ  3330981  5.64  3    31   [ΚΑΙ]  1
25     ΔΕ  1361502  2.30  2     9    [ΔΕ]  1
309    ΤΟ  1291657  2.19  2   370    [ΤΟ]  1
46    ΤΟΥ   927927  1.57  3   770   [ΤΟΥ]  1
2     ΤΩΝ   914800  1.55  3  1150   [ΤΩΝ]  1
101     Η   880934  1.49  1     8     [Η]  1
26    ΤΗΝ   800865  1.36  3   358   [ΤΗΝ]  1
11     ΕΝ   710521  1.20  2    55    [ΕΝ]  1
224     Ο   673358  1.14  1    70     [Ο]  1
216   ΤΗΣ   671515  1.14  3   508   [ΤΗΣ]  1
88    ΓΑΡ   635979  1.08  3   104   [ΓΑΡ]  1
95    ΜΕΝ   595351  1.01  3    95   [ΜΕΝ]  1
168    ΤΑ   551929  0.93  2   301    [ΤΑ]  1
241   ΤΟΝ   518764  0.88  3   420   [ΤΟΝ]  1
147    ΤΩ   463122  0.78  2  1100    [ΤΩ]  1
15     ΩΣ   394803  0.67  2  1000    [ΩΣ]  1
308   ΕΙΣ   351612  0.60  3   215   [ΕΙΣ]  1
27     ΤΕ   340375  0.58  2   305    [ΤΕ]  1
119    ΟΥ   335887  0.57  2   470    [ΟΥ]  1
20   ΠΡΟΣ   331253  0.56  4   450  [ΠΡΟΣ]  1

## Solve the riddles

### Riddle 1

Using the next parameters from the riddle, lets try to solve it by the brute computational force:

- knowing the isopsephical value: 1697
- knowing the length of the word: 9
- knowing the count of the consonants of the word: 5
- knowing other details of the syllables of the word
- comparing the context of the result

#### Isopsephy and letter count filter

So, how many words there are with the isopsephical value 1697 and letters counting nine?

In [5]:
# make a copy of the database to keep original safe
a = df.copy()
# filter by isopsephical value
a = a[a[4] == 1697]
# filter by word length
a = a[a[3] == 9]

print("Total records: %s" % len(a))
a

Total records: 15

                0    1    2  3     4                    5  6
37510   ΑΜΦΕΚΑΛΥΨ    1  0.0  9  1697    [ΑΜ, ΦΕ, ΚΑ, ΛΥΨ]  4
91309   ΑΛΕΙΦΑΤΩΝ    2  0.0  9  1697    [Α, ΛΕΙ, ΦΑ, ΤΩΝ]  4
108960  ΒΕΛΤΙΣΤΩΝ   67  0.0  9  1697      [ΒΕΛ, ΤΙ, ΣΤΩΝ]  3
111871  ΑΦΕΛΩΝΤΑΙ   19  0.0  9  1697    [Α, ΦΕ, ΛΩΝ, ΤΑΙ]  4
115565  ΠΑΡΑΧΩΡΕΙ  128  0.0  9  1697    [ΠΑ, ΡΑ, ΧΩ, ΡΕΙ]  4
115604  ΚΥΒΕΥΣΟΥΣ    1  0.0  9  1697      [ΚΥ, ΒΕΥ, ΣΟΥΣ]  3
215046  ΛΙΒΥΣΣΕΩΝ    2  0.0  9  1697    [ΛΙ, ΒΥΣ, ΣΕ, ΩΝ]  4
242375  ΙΣΤΟΡΗΣΘΩ    9  0.0  9  1697    [Ι, ΣΤΟ, ΡΗ, ΣΘΩ]  4
341688  ΣΥΝΩΚΙΣΘΗ   19  0.0  9  1697    [ΣΥ, ΝΩ, ΚΙ, ΣΘΗ]  4
518578  ΠΛΗΡΟΥΣΘΩ    7  0.0  9  1697      [ΠΛΗ, ΡΟΥ, ΣΘΩ]  3
657601  ΕΚΑΑΤΟΣΤΩ    3  0.0  9  1697  [Ε, ΚΑ, Α, ΤΟ, ΣΤΩ]  5
711650  ΛΗΛΥΘΟΤΩΝ    3  0.0  9  1697    [ΛΗ, ΛΥ, ΘΟ, ΤΩΝ]  4
777732  ΑΝΑΝΨΩΜΕΝ    4  0.0  9  1697    [Α, ΝΑΝ, ΨΩ, ΜΕΝ]  4
780718  ΑΛΕΦΩΝΤΑΙ    2  0.0  9  1697    [Α, ΛΕ, ΦΩΝ, ΤΑΙ]  4
796540  ΣΤΕΝΩΜΑΤΑ    8  0.0  9  1697    [ΣΤΕ, ΝΩ, ΜΑ, ΤΑ]  4

It turns out that there are just very few words meeting the criteria of the riddle. I could already make the analysis of the words manually. But to make everything reusable for later usage, I will set up filter procedure for other criteria too.

Before that, I will however add one extension to the original search and allow the count of the letters to be between 8 and 10. That is due to double consonant and long / short vowelspecialty of the Greek language. Let's see the result of this filter variation:

In [6]:
b = df.copy()
b = b[b[4] == 1697]
b = b[b[6] == 4]
b = b[b[3] > 7]
b = b[b[3] < 11]

print("Total records: %s" % len(b))
b.sort_values(3, ascending=False)

Total records: 32

                 0    1    2   3     4                   5  6
28950   ΚΑΤΑΣΧΕΤΟΣ   18  0.0  10  1697  [ΚΑ, ΤΑ, ΣΧΕ, ΤΟΣ]  4
312687  ΚΑΤΑΨΥΞΕΙΣ   30  0.0  10  1697  [ΚΑ, ΤΑ, ΨΥ, ΞΕΙΣ]  4
714771  ΑΝΕΣΤΛΩΤΑΙ    3  0.0  10  1697  [Α, ΝΕΣΤ, ΛΩ, ΤΑΙ]  4
617168  ΕΜΦΥΣΣΑΝΤΑ    9  0.0  10  1697  [ΕΜ, ΦΥΣ, ΣΑΝ, ΤΑ]  4
612383  ΑΚΑΤΣΧΕΤΟΣ   27  0.0  10  1697  [Α, ΚΑΤ, ΣΧΕ, ΤΟΣ]  4
603707  ΕΠΤΑΠΛΑΣΩΣ   18  0.0  10  1697  [Ε, ΠΤΑ, ΠΛΑ, ΣΩΣ]  4
602801  ΠΑΡΑΙΤΣΕΩΣ   23  0.0  10  1697  [ΠΑ, ΡΑΙΤ, ΣΕ, ΩΣ]  4
539506  ΕΥΗΘΕΣΤΤΟΥ    4  0.0  10  1697  [ΕΥ, Η, ΘΕΣΤ, ΤΟΥ]  4
526576  ΚΑΤΑΨΥΞΕΙϹ    2  0.0  10  1697  [ΚΑ, ΤΑ, ΨΥ, ΞΕΙϹ]  4
432804  ΔΙΕΣΤΗΚΤΩΝ   56  0.0  10  1697  [ΔΙ, Ε, ΣΤΗ, ΚΤΩΝ]  4
425953  ΥΦΙΖΝΟΥΣΙΝ    3  0.0  10  1697  [Υ, ΦΙΖ, ΝΟΥ, ΣΙΝ]  4
344849  ΧΑΜΑΙΖΗΛΩΣ    3  0.0  10  1697  [ΧΑ, ΜΑΙ, ΖΗ, ΛΩΣ]  4
804994  ΠΑΧΥΤΕΡΑΙΣ    8  0.0  10  1697  [ΠΑ, ΧΥ, ΤΕ, ΡΑΙΣ]  4
288752  ΠΑΡΕΣΤΩΣΑΙ    2  0.0  10  1697  [ΠΑ, ΡΕ, ΣΤΩ, ΣΑΙ]  4
275891  ΝΕΒΡΟΦΟΝΩΝ    1  0.0  10  1697  [ΝΕ, ΒΡΟ, ΦΟ, ΝΩΝ]  4
66089   ΡΑΒΔΟΦΟΡΩΝ    3  0.0  10  1697  [ΡΑ, ΒΔΟ, ΦΟ, ΡΩΝ]  4
341688   ΣΥΝΩΚΙΣΘΗ   19  0.0   9  1697   [ΣΥ, ΝΩ, ΚΙ, ΣΘΗ]  4
796540   ΣΤΕΝΩΜΑΤΑ    8  0.0   9  1697   [ΣΤΕ, ΝΩ, ΜΑ, ΤΑ]  4
780718   ΑΛΕΦΩΝΤΑΙ    2  0.0   9  1697   [Α, ΛΕ, ΦΩΝ, ΤΑΙ]  4
777732   ΑΝΑΝΨΩΜΕΝ    4  0.0   9  1697   [Α, ΝΑΝ, ΨΩ, ΜΕΝ]  4
711650   ΛΗΛΥΘΟΤΩΝ    3  0.0   9  1697   [ΛΗ, ΛΥ, ΘΟ, ΤΩΝ]  4
91309    ΑΛΕΙΦΑΤΩΝ    2  0.0   9  1697   [Α, ΛΕΙ, ΦΑ, ΤΩΝ]  4
111871   ΑΦΕΛΩΝΤΑΙ   19  0.0   9  1697   [Α, ΦΕ, ΛΩΝ, ΤΑΙ]  4
115565   ΠΑΡΑΧΩΡΕΙ  128  0.0   9  1697   [ΠΑ, ΡΑ, ΧΩ, ΡΕΙ]  4
215046   ΛΙΒΥΣΣΕΩΝ    2  0.0   9  1697   [ΛΙ, ΒΥΣ, ΣΕ, ΩΝ]  4
242375   ΙΣΤΟΡΗΣΘΩ    9  0.0   9  1697   [Ι, ΣΤΟ, ΡΗ, ΣΘΩ]  4
37510    ΑΜΦΕΚΑΛΥΨ    1  0.0   9  1697   [ΑΜ, ΦΕ, ΚΑ, ΛΥΨ]  4
110969    ΑΝΕΜΦΑΤΩ    1  0.0   8  1697    [Α, ΝΕΜ, ΦΑ, ΤΩ]  4
640678    ΦΟΒΗΘΗΤΩ    2  0.0   8  1697    [ΦΟ, ΒΗ, ΘΗ, ΤΩ]  4
150598    ΧΩΣΑΜΕΝΑ    1  0.0   8  1697    [ΧΩ, ΣΑ, ΜΕ, ΝΑ]  4
369976    ΦΩΤΟΕΙΔΗ   28  0.0   8  1697    [ΦΩ, ΤΟ, ΕΙ, ΔΗ]  4
373378    ΠΥΡΕΤΩΔΗ   61  0.0   8  1697    [ΠΥ, ΡΕ, ΤΩ, ΔΗ]  4

But this was for the experiment only for now. I will stick on the more strict parameters in the following riddle solver.

#### Custom syllable filter

There is still two other criterias for the word filter. One is a bit more problematic. Poem says there are two letters in the first three syllables. And the rest of the letters, that is three, are in the last syllable. But I don't need to specify the last syllable letter count because I already limit total letter count to nine. If the first three syllables contain 2 letters, that is 6 in total, then the last must have the rest 3 letters.

The fifth column has appropriate syllable information that I can use for this kind of filter. Let's see the result with this and all the previous filters:

In [7]:
c = df.copy()
c = c[c[4] == 1697]
c = c[c[6] == 4]
c = c[c[3] == 9]
# the first three of the syllable contain two letters, the last one the rest i.e. three.
c = c[c.apply(lambda x: len(x[5][0]) == 2 and len(x[5][1]) == 2 and len(x[5][2]) == 2, axis=1)]

print("Total records: %s" % len(c))
c.sort_values(0)

Total records: 4

                0    1    2  3     4                  5  6
37510   ΑΜΦΕΚΑΛΥΨ    1  0.0  9  1697  [ΑΜ, ΦΕ, ΚΑ, ΛΥΨ]  4
711650  ΛΗΛΥΘΟΤΩΝ    3  0.0  9  1697  [ΛΗ, ΛΥ, ΘΟ, ΤΩΝ]  4
115565  ΠΑΡΑΧΩΡΕΙ  128  0.0  9  1697  [ΠΑ, ΡΑ, ΧΩ, ΡΕΙ]  4
341688  ΣΥΝΩΚΙΣΘΗ   19  0.0  9  1697  [ΣΥ, ΝΩ, ΚΙ, ΣΘΗ]  4

#### Consonant filter

Finally there is the rule of five consonants (mutes/males) in the word in the original riddle. That requires defining the consonants list and checking that the total count of the consonants is exactly five, no more, no less. I will do an exercise to filter all words having 4 syllables and 5 consonants.

In [8]:
d = df.copy()
d = d[d[4] == 1697]
d = d[d[6] == 4]
d = d[d[3] == 9]
d = d[d.apply(lambda x: sum(list(x[0].count(c) for c in "ΨΖΞΒΦΧΘΓΔΜΛΚΠΡΣΤ")) == 5, axis=1)]

print("Total records: %s" % len(d))
d.sort_values(0)

Total records: 2

                0  1    2  3     4                  5  6
37510   ΑΜΦΕΚΑΛΥΨ  1  0.0  9  1697  [ΑΜ, ΦΕ, ΚΑ, ΛΥΨ]  4
242375  ΙΣΤΟΡΗΣΘΩ  9  0.0  9  1697  [Ι, ΣΤΟ, ΡΗ, ΣΘΩ]  4

Let's refactor all of this and the previous ones to the single callable function with reusable sub functions and apply it to dataframe.

In [9]:
# the word should have n mutes ie consonants
consonants = "ΨΖΞΒΦΧΘΓΔΜΛΚΠΡΣΤΝϹϚϠϞ"
def nmutes(x, n):
    word, tot = x[0], 0
    for c in consonants:
        tot += word.count(c)
        if tot > n:
            return False
    return tot == n

# the word should have n vowels
vowels = "ϒΩΗΥΕΙΟΑ"
def nvowels(x, n):
    word, tot = x[0], 0
    for c in vowels:
        tot += word.count(c)
        if tot > n:
            return False
    return tot == n

# the word should have n syllables
def nsyllables(x, n):
    return x[6] == n

# the word should have two letters in the first three syllables, and the rest (3) letters in the last
def has_two_letters_in_first_three_syllables(x):
    return len(x[5][0]) == 2 and len(x[5][1]) == 2 and len(x[5][2]) == 2

# this makes n letters in total
def nletters(x, n):
    return x[3] == n

# isopsephical value
def nisopsephy(x, n):
    return x[4] > n[0] and x[4] < n[1] if type(n) is list else x[4] == n

# riddle wrapper function
def riddle(x, isopsephy, letters = 9, mutes = 5, syllables = 4):
    return nisopsephy(x, isopsephy) and nsyllables(x, syllables) and \
           nletters(x, letters) and nmutes(x, mutes) and \
           has_two_letters_in_first_three_syllables(x)

In [10]:
# solve the riddle
e = df.copy()
e = e[e.apply(lambda x: riddle(x, 1697), axis=1)]
e

                0   1    2  3     4                  5  6
37510   ΑΜΦΕΚΑΛΥΨ   1  0.0  9  1697  [ΑΜ, ΦΕ, ΚΑ, ΛΥΨ]  4
341688  ΣΥΝΩΚΙΣΘΗ  19  0.0  9  1697  [ΣΥ, ΝΩ, ΚΙ, ΣΘΗ]  4
711650  ΛΗΛΥΘΟΤΩΝ   3  0.0  9  1697  [ΛΗ, ΛΥ, ΘΟ, ΤΩΝ]  4

Thus we have found three good matches for the riddle: ΑΜΦΕΚΑΛΥΨ, ΣΥΝΩΚΙΣΘΗ, and ΛΗΛΥΘΟΤΩΝ. From these, the word especially interesting is:

# ΑΜΦΕΚΑΛΥΨ

(amphekalyps / amfecalyps) meaning "covering from both sides" or "all around covering".

Next we should make some text and linquistic examination, how well these proposed words fits to the immediate context of the sibylline verses. Where are the exact occurrences of the word in the Greek corpora, in which context? Is it a word suitable for an epithet, does it have any religious spiritual significance, and so forth. These questions I will leave for the other study.

### Riddle 2

In [11]:
# solve the riddle
f = df.copy()
f = f[f.apply(lambda x: riddle(x, 506), axis=1)]
f

                0     1    2  3    4                  5  6
7177    ΜΕΤΑΒΟΛΗΝ  2654  0.0  9  506  [ΜΕ, ΤΑ, ΒΟ, ΛΗΝ]  4
27790   ΑΡΣΕΝΙΚΟΝ   336  0.0  9  506  [ΑΡ, ΣΕ, ΝΙ, ΚΟΝ]  4
77173   ΑΝΤΕΛΕΞΕΝ     4  0.0  9  506  [ΑΝ, ΤΕ, ΛΕ, ΞΕΝ]  4
139165  ΠΕΠΗΓΟΣΙΝ     7  0.0  9  506  [ΠΕ, ΠΗ, ΓΟ, ΣΙΝ]  4
407770  ΑΡϹΕΝΙΚΟΝ   209  0.0  9  506  [ΑΡ, ϹΕ, ΝΙ, ΚΟΝ]  4
437866  ΑϹΠΑΡΑΓΟΝ    10  0.0  9  506  [ΑϹ, ΠΑ, ΡΑ, ΓΟΝ]  4
448532  ΑΡΤΙΓΑΛΑΞ     3  0.0  9  506  [ΑΡ, ΤΙ, ΓΑ, ΛΑΞ]  4
526936  ΘΗΡΑΤΙΚΗΝ     2  0.0  9  506  [ΘΗ, ΡΑ, ΤΙ, ΚΗΝ]  4
566733  ΠΙΝΟΜΕΝΑϹ     3  0.0  9  506  [ΠΙ, ΝΟ, ΜΕ, ΝΑϹ]  4
664241  ΕΓΓΙΖΟΣΗΣ     9  0.0  9  506  [ΕΓ, ΓΙ, ΖΟ, ΣΗΣ]  4

### Riddle 3

In [12]:
# solve the riddle
g = df.copy()
g = g[g.apply(lambda x: riddle(x, 1496), axis=1)]
g

                0    1    2  3     4                  5  6
25522   ΤΕΛΑΜΩΝΟΣ  159  0.0  9  1496  [ΤΕ, ΛΑ, ΜΩ, ΝΟΣ]  4
64849   ΣΥΝΕΚΟΨΑΝ    2  0.0  9  1496  [ΣΥ, ΝΕ, ΚΟ, ΨΑΝ]  4
152540  ΚΕΚΩΛΥΚΑΣ    9  0.0  9  1496  [ΚΕ, ΚΩ, ΛΥ, ΚΑΣ]  4
272986  ΠΑΡΩΤΙΔΑΣ  142  0.0  9  1496  [ΠΑ, ΡΩ, ΤΙ, ΔΑΣ]  4
374466  ΣΩΡΗΤΙΚΗΝ    2  0.0  9  1496  [ΣΩ, ΡΗ, ΤΙ, ΚΗΝ]  4
389356  ΠΙΝΕΤΩΣΑΝ    9  0.0  9  1496  [ΠΙ, ΝΕ, ΤΩ, ΣΑΝ]  4
405610  ΠΙΝΕΤΩϹΑΝ   11  0.0  9  1496  [ΠΙ, ΝΕ, ΤΩ, ϹΑΝ]  4
438655  ΤΕΛΑΜΩΝΟϹ   17  0.0  9  1496  [ΤΕ, ΛΑ, ΜΩ, ΝΟϹ]  4
469721  ΤΑΠΕΝΩΣΙΝ  102  0.0  9  1496  [ΤΑ, ΠΕ, ΝΩ, ΣΙΝ]  4
566209  ΠΑΡΩΤΙΔΑϹ    3  0.0  9  1496  [ΠΑ, ΡΩ, ΤΙ, ΔΑϹ]  4
650303  ΠΕΝΙΩΝΤΑΣ    3  0.0  9  1496  [ΠΕ, ΝΙ, ΩΝ, ΤΑΣ]  4
770042  ΑΜΤΕΛΩΝΟΣ    4  0.0  9  1496  [ΑΜ, ΤΕ, ΛΩ, ΝΟΣ]  4

## The [MIT](http://choosealicense.com/licenses/mit/) License

Copyright &copy; 2018 Marko Manninen